name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.LAUNDRY_CI }}
        TARGET_REPO: yannickspoerl/blog
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm && npm build
        BUILD_DIR: blog/.vuepress/dist/